line-length = 100
target-version = "py312"
exclude = ["venv", ".venv", "build", "dist", "node_modules"]

[lint]
select = ["E","F","I","N","B","UP","C90","S","W","PL"]
ignore = [
    "S101", "B008", "E501", "S105", "S310", "B904", "PLR0912",
    "C901", "PLR0913", "PLR2004", "PLR0915", "PLW0603", "PLW0602", "S110"
]  # Broad ignores for existing codebase complexity and style


[lint.per-file-ignores]
"tests/**" = ["PLR2004"]  # allow '200' etc. in tests
